### ISSUE TITLE
install on onprem kubernetes cluster v1.12.3

### ISSUE THREAD

**Issue by mflpopescu** [operator-framework/operator-metering#557]
Hello, I'm trying to install operator-metering in an onprem kubernetes cluster running v1.12.3 and using a custom configuration file

My custom config is picked up and deployed to the metering namespace 

After installing using _./hack/install.sh_ only the metering-operator pod is created and then stuck in _CrashLoopBackOff_ . I can see several errors in containers metering-operator and tiller related to unavailability of apiVersion "monitoring.coreos.com/v1"

**metering-operator container errors**
```
$ kubectl logs metering-operator-68b7dc66b9-6tl5s -n metering -c metering-operator
Running helm upgrade for release operator-metering
Using /openshift-metering-0.1.0.tgz as chart
Release "operator-metering" does not exist. Installing it now.
Error: apiVersion "monitoring.coreos.com/v1" in openshift-metering/templates/presto-service-monitor.yaml is not available
```

```
export METERING_NAMESPACE=metering
export METERING_CR_FILE=metering-custom.yaml
```

```
kubectl get metering -n metering
NAME                AGE
operator-metering   23m
```

**custom config to specify prometheus endpoint**
```
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      config:
        prometheusURL: "http://obfuscated.svc:8080"
        tls:
          enabled: false
        metricsTLS:
          enabled: false
  presto:
    spec:
      presto:
        securityContext:
          fsGroup: 0
      hive:
        securityContext:
          fsGroup: 0
  hdfs:
    spec:
      securityContext:
        fsGroup: 0
  image:
    repository: quay.io/coreos/metering-reporting-operator
    tag: latest
```

**tiller container errors**
```
$ kubectl logs metering-operator-68b7dc66b9-x7rvl -n metering -c tiller
[main] 2019/01/09 16:39:01 Starting Tiller 1.10.3+unreleased (tls=false)
[main] 2019/01/09 16:39:01 GRPC listening on :44134
[main] 2019/01/09 16:39:01 Probes listening on :44135
[main] 2019/01/09 16:39:01 Storage driver is ConfigMap
[main] 2019/01/09 16:39:01 Max history per release is 3
[tiller] 2019/01/09 16:39:08 getting history for release operator-metering
[storage] 2019/01/09 16:39:08 getting release history for "operator-metering"
[tiller] 2019/01/09 16:39:09 preparing install for operator-metering
[storage] 2019/01/09 16:39:09 getting release history for "operator-metering"
[tiller] 2019/01/09 16:39:09 rendering openshift-metering chart using values
2019/01/09 16:39:10 info: manifest "openshift-metering/charts/openshift-reporting/templates/report-queries/pod-cpu-aws.yaml" is empty. Skipping.
2019/01/09 16:39:10 info: manifest "openshift-metering/charts/openshift-reporting/templates/report-queries/aws-billing.yaml" is empty. Skipping.
[tiller] 2019/01/09 16:39:10 failed install prepare step: apiVersion "monitoring.coreos.com/v1" in openshift-metering/templates/reporting-operator-service-monitor.yaml is not available
[tiller] 2019/01/09 16:39:21 getting history for release operator-metering
[storage] 2019/01/09 16:39:21 getting release history for "operator-metering"
[tiller] 2019/01/09 16:39:21 preparing install for operator-metering
[storage] 2019/01/09 16:39:21 getting release history for "operator-metering"
[tiller] 2019/01/09 16:39:21 rendering openshift-metering chart using values
2019/01/09 16:39:22 info: manifest "openshift-metering/charts/openshift-reporting/templates/report-queries/aws-billing.yaml" is empty. Skipping.
2019/01/09 16:39:22 info: manifest "openshift-metering/charts/reporting-operator/templates/reporting-operator-auth-proxy-rbac.yaml" is empty. Skipping.
2019/01/09 16:39:23 info: manifest "openshift-metering/charts/reporting-operator/templates/reporting-operator-auth-proxy-htpasswd-secret.yaml" is empty. Skipping.
2019/01/09 16:39:23 info: manifest "openshift-metering/charts/reporting-operator/templates/reporting-operator-auth-proxy-authenticated-emails-secret.yaml" is empty. Skipping.
2019/01/09 16:39:23 info: manifest "openshift-metering/charts/openshift-reporting/templates/report-queries/pod-memory-aws.yaml" is empty. Skipping.
2019/01/09 16:39:23 info: manifest "openshift-metering/charts/reporting-operator/templates/route.yaml" is empty. Skipping.
[tiller] 2019/01/09 16:39:23 failed install prepare step: apiVersion "monitoring.coreos.com/v1" in openshift-metering/templates/reporting-operator-service-monitor.yaml is not available
[tiller] 2019/01/09 16:39:46 getting history for release operator-metering
[storage] 2019/01/09 16:39:46 getting release history for "operator-metering"
[tiller] 2019/01/09 16:39:47 preparing install for operator-metering
[storage] 2019/01/09 16:39:47 getting release history for "operator-metering"
[tiller] 2019/01/09 16:39:47 rendering openshift-metering chart using values
2019/01/09 16:39:48 info: manifest "openshift-metering/charts/reporting-operator/templates/route.yaml" is empty. Skipping.
2019/01/09 16:39:48 info: manifest "openshift-metering/charts/reporting-operator/templates/reporting-operator-auth-proxy-rbac.yaml" is empty. Skipping.
2019/01/09 16:39:48 info: manifest "openshift-metering/charts/presto/templates/shared-volume-pvc.yaml" is empty. Skipping.
2019/01/09 16:39:48 info: manifest "openshift-metering/charts/openshift-reporting/templates/report-queries/pod-memory-aws.yaml" is empty. Skipping.
2019/01/09 16:39:49 info: manifest "openshift-metering/charts/reporting-operator/templates/reporting-operator-auth-proxy-authenticated-emails-secret.yaml" is empty. Skipping.
2019/01/09 16:39:49 info: manifest "openshift-metering/charts/openshift-reporting/templates/report-queries/aws-billing.yaml" is empty. Skipping.
[tiller] 2019/01/09 16:39:49 failed install prepare step: apiVersion "monitoring.coreos.com/v1" in openshift-metering/templates/reporting-operator-service-monitor.yaml is not available
[tiller] 2019/01/09 16:40:24 getting history for release operator-metering
[storage] 2019/01/09 16:40:24 getting release history for "operator-metering"
[tiller] 2019/01/09 16:40:25 preparing install for operator-metering
[storage] 2019/01/09 16:40:25 getting release history for "operator-metering"
[tiller] 2019/01/09 16:40:25 rendering openshift-metering chart using values
2019/01/09 16:40:26 info: manifest "openshift-metering/charts/openshift-reporting/templates/report-queries/aws-billing.yaml" is empty. Skipping.
2019/01/09 16:40:26 info: manifest "openshift-metering/charts/reporting-operator/templates/route.yaml" is empty. Skipping.
[tiller] 2019/01/09 16:40:26 failed install prepare step: apiVersion "monitoring.coreos.com/v1" in openshift-metering/templates/presto-service-monitor.yaml is not available
[tiller] 2019/01/09 16:42:51 getting history for release operator-metering
[storage] 2019/01/09 16:42:51 getting release history for "operator-metering"
[tiller] 2019/01/09 16:42:52 preparing install for operator-metering
[storage] 2019/01/09 16:42:52 getting release history for "operator-metering"
[tiller] 2019/01/09 16:42:52 rendering openshift-metering chart using values
2019/01/09 16:42:53 info: manifest "openshift-metering/charts/reporting-operator/templates/reporting-operator-auth-proxy-authenticated-emails-secret.yaml" is empty. Skipping.
2019/01/09 16:42:53 info: manifest "openshift-metering/charts/reporting-operator/templates/route.yaml" is empty. Skipping.
2019/01/09 16:42:53 info: manifest "openshift-metering/charts/openshift-reporting/templates/report-queries/pod-memory-aws.yaml" is empty. Skipping.
2019/01/09 16:42:53 info: manifest "openshift-metering/charts/presto/templates/shared-volume-pvc.yaml" is empty. Skipping.
2019/01/09 16:42:53 info: manifest "openshift-metering/charts/reporting-operator/templates/reporting-operator-auth-proxy-rbac.yaml" is empty. Skipping.
2019/01/09 16:42:53 info: manifest "openshift-metering/charts/reporting-operator/templates/reporting-operator-auth-proxy-htpasswd-secret.yaml" is empty. Skipping.
[tiller] 2019/01/09 16:42:53 failed install prepare step: apiVersion "monitoring.coreos.com/v1" in openshift-metering/templates/reporting-operator-service-monitor.yaml is not available
[tiller] 2019/01/09 16:45:55 getting history for release operator-metering
[storage] 2019/01/09 16:45:55 getting release history for "operator-metering"
[tiller] 2019/01/09 16:45:56 preparing install for operator-metering
[storage] 2019/01/09 16:45:56 getting release history for "operator-metering"
[tiller] 2019/01/09 16:45:56 rendering openshift-metering chart using values
2019/01/09 16:45:57 info: manifest "openshift-metering/charts/reporting-operator/templates/reporting-operator-auth-proxy-rbac.yaml" is empty. Skipping.
[tiller] 2019/01/09 16:45:57 failed install prepare step: apiVersion "monitoring.coreos.com/v1" in openshift-metering/templates/reporting-operator-service-monitor.yaml is not available
[tiller] 2019/01/09 16:51:14 getting history for release operator-metering
[storage] 2019/01/09 16:51:14 getting release history for "operator-metering"
[tiller] 2019/01/09 16:51:15 preparing install for operator-metering
[storage] 2019/01/09 16:51:15 getting release history for "operator-metering"
[tiller] 2019/01/09 16:51:15 rendering openshift-metering chart using values
[tiller] 2019/01/09 16:51:16 failed install prepare step: apiVersion "monitoring.coreos.com/v1" in openshift-metering/templates/reporting-operator-service-monitor.yaml is not available
```

**Comment by chancez** [comment]
Ah, that's because a recent PR that enables serviceMonitors by default. You can disable that by setting  `spec.monitoring.enabled` to `false` in your Metering CR.

**Comment by mflpopescu** [comment]
Wonderful, setting `spec.monitoring.enabled` was what was missing to nudge it. But now I see pods `hdfs-datanode-0` and `metering-operator-68b7dc66b9-bfddf` in `CrashLoopBackOff`

```
$ kubectl get pods -n metering
NAME                                  READY   STATUS             RESTARTS   AGE
hdfs-datanode-0                       0/1     CrashLoopBackOff   3          100s
hdfs-namenode-0                       1/1     Running            0          64m
hive-metastore-0                      1/1     Running            0          64m
hive-server-0                         1/1     Running            0          64m
metering-operator-68b7dc66b9-bfddf    1/2     CrashLoopBackOff   13         65m
presto-coordinator-6fd8ccf876-vdvrh   1/1     Running            0          64m
reporting-operator-75f4ff4cf-kmwfk    0/1     Running            9          64m
```

```
$ kubectl logs hdfs-datanode-0 -n metering
2019-01-09 23:46:14,359 WARN checker.StorageLocationChecker: Exception checking StorageLocation [DISK]file:/hadoop/dfs/data
EPERM: Operation not permitted
	at org.apache.hadoop.io.nativeio.NativeIO$POSIX.chmodImpl(Native Method)
	at org.apache.hadoop.io.nativeio.NativeIO$POSIX.chmod(NativeIO.java:233)
	at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:836)
	at org.apache.hadoop.fs.ChecksumFileSystem$1.apply(ChecksumFileSystem.java:508)
	at org.apache.hadoop.fs.ChecksumFileSystem$FsOperation.run(ChecksumFileSystem.java:489)
	at org.apache.hadoop.fs.ChecksumFileSystem.setPermission(ChecksumFileSystem.java:511)
	at org.apache.hadoop.util.DiskChecker.mkdirsWithExistsAndPermissionCheck(DiskChecker.java:234)
	at org.apache.hadoop.util.DiskChecker.checkDirInternal(DiskChecker.java:141)
	at org.apache.hadoop.util.DiskChecker.checkDir(DiskChecker.java:116)
	at org.apache.hadoop.hdfs.server.datanode.StorageLocation.check(StorageLocation.java:239)
	at org.apache.hadoop.hdfs.server.datanode.StorageLocation.check(StorageLocation.java:52)
	at org.apache.hadoop.hdfs.server.datanode.checker.ThrottledAsyncChecker$1.call(ThrottledAsyncChecker.java:142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-01-09 23:46:14,451 ERROR datanode.DataNode: Exception in secureMain
org.apache.hadoop.util.DiskChecker$DiskErrorException: Too many failed volumes - current valid volumes: 0, volumes configured: 1, volumes failed: 1, volume failures tolerated: 0
	at org.apache.hadoop.hdfs.server.datanode.checker.StorageLocationChecker.check(StorageLocationChecker.java:220)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.makeInstance(DataNode.java:2762)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.instantiateDataNode(DataNode.java:2677)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.createDataNode(DataNode.java:2719)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.secureMain(DataNode.java:2863)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.main(DataNode.java:2887)
2019-01-09 23:46:14,452 INFO util.ExitUtil: Exiting with status 1: org.apache.hadoop.util.DiskChecker$DiskErrorException: Too many failed volumes - current valid volumes: 0, volumes configured: 1, volumes failed: 1, volume failures tolerated: 0
2019-01-09 23:46:14,454 INFO datanode.DataNode: SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down DataNode at hdfs-datanode-0.hdfs-datanode.metering.svc.cluster.local/obfuscated
```

I submitted a report using `kubectl -n metering create -f ./report-ns-cpu.yaml`
```
$ more report-ns-cpu.yaml 
apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: namespace-cpu-request1
spec:
  reportingStart: '2019-01-09T00:00:00Z'
  reportingEnd: '2018-01-09T23:00:00Z'
  generationQuery: "namespace-cpu-request"
  runImmediately: true
```

report can be viewed
```
$ kubectl get report -n metering
NAME                     QUERY                   SCHEDULE   RUNNING   FAILED   TABLE NAME   LAST REPORT TIME   AGE
namespace-cpu-request    namespace-cpu-request                                                                 53m
namespace-cpu-request1   namespace-cpu-request                                                                 20m
```

but I suppose is never executed. When trying to retrieve it it appears it has not been executed
```
kubectl port-forward svc/reporting-operator 8081:8080 -n metering
curl http://localhost:8081/api/v1/reports/get?name=namespace-cpu-request&format=tab
{"error":"Report is not processed yet"}
```

**Comment by chancez** [comment]
What kind of storage are you using for PVCs? Is this a hostVolume?

**Comment by chancez** [comment]
Okay, it would seem the permissions to access the volume as non-root are working, probably because you changed fsGroup to 0. You may need the following config to work-around this:

```
  hdfs:
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        fsGroup: 0
```

**Comment by mflpopescu** [comment]
that was it ! 
thanks, chancez
