### ISSUE TITLE
Delete Hive Row 

### ISSUE THREAD

**Issue by JooyoungJeong** [operator-framework/operator-metering#733]
Hi. 

How can I delete row in hive table?
I want to delete a row when an undesired value is inserted.
Metering version 0.14

Ex. 
```
delete from datasource_metering_node_allocatable_cpu_cores where labels['node']='ip-172-20-60-40.us-west-2.compute.internal';
```
Error message
```
hive> 
    > delete from datasource_metering_node_allocatable_cpu_cores where labels['node']='ip-172-20-60-40.us-west-2.compute.internal';
19/05/31 04:40:16 [main]: INFO conf.HiveConf: Using the default value passed in for log id: ddbb4580-c710-4e5a-be51-f10d0cc1d10c
19/05/31 04:40:16 [main]: INFO session.SessionState: Updating thread name to ddbb4580-c710-4e5a-be51-f10d0cc1d10c main
19/05/31 04:40:16 [ddbb4580-c710-4e5a-be51-f10d0cc1d10c main]: INFO ql.Driver: Compiling command(queryId=hadoop_20190531044016_8c32c833-7d5a-40a3-bca4-0aad6a468bc6): delete from datasource_metering_node_allocatable_cpu_cores where labels['node']='ip-172-20-60-40.us-west-2.compute.internal'
FAILED: SemanticException [Error 10294]: Attempt to do update or delete using transaction manager that does not support these operations.
19/05/31 04:40:16 [ddbb4580-c710-4e5a-be51-f10d0cc1d10c main]: ERROR ql.Driver: FAILED: SemanticException [Error 10294]: Attempt to do update or delete using transaction manager that does not support these operations.
org.apache.hadoop.hive.ql.parse.SemanticException: Attempt to do update or delete using transaction manager that does not support these operations.
        at org.apache.hadoop.hive.ql.parse.UpdateDeleteSemanticAnalyzer.analyzeInternal(UpdateDeleteSemanticAnalyzer.java:77)
        at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.analyze(BaseSemanticAnalyzer.java:258)
        at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:512)
        at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1317)
        at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1457)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1237)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1227)
        at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:233)
        at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:184)
        at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:403)
        at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:821)
        at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:759)
        at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:686)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:318)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:232)

19/05/31 04:40:16 [ddbb4580-c710-4e5a-be51-f10d0cc1d10c main]: INFO conf.HiveConf: Using the default value passed in for log id: ddbb4580-c710-4e5a-be51-f10d0cc1d10c
19/05/31 04:40:16 [ddbb4580-c710-4e5a-be51-f10d0cc1d10c main]: INFO ql.Driver: Completed compiling command(queryId=hadoop_20190531044016_8c32c833-7d5a-40a3-bca4-0aad6a468bc6); Time taken: 0.004 seconds
19/05/31 04:40:16 [ddbb4580-c710-4e5a-be51-f10d0cc1d10c main]: INFO session.SessionState: Resetting thread name to  main
```

Thank  you.

**Comment by chancez** [comment]
Currently not supported. You would be required to delete entire partitions (meaning an entire day of data), if it was supported. But today we don't enable the configuration options to allow deletes or updates, as that requires other changes.
